### ISSUE TITLE
ALPN_H2_WIRE constant may be incorrect

### ISSUE THREAD

**Issue by lvkv** [LucioFranco/tonic-openssl#8]
There's a leading `\x02` here that [isn't in the RFC](https://datatracker.ietf.org/doc/html/rfc7540#section-3.1), which instead specifies `b"h2"`:
https://github.com/LucioFranco/tonic-openssl/blob/bdaaecda437949244a1b4d61cb39110c4bcad019/src/lib.rs#L31

I could be wrong, but this appears to have been a holdover from the transition from NPN to ALPN.

**Comment by G1gg1L3s** [comment]
It's probably this OpenSSL-specific encoding - https://www.openssl.org/docs/man3.3/man3/SSL_set_alpn_protos.html#NOTES

**Comment by lvkv** [comment]
Ah, so there's a leading 2 there because the length of `"h2"` is 2. I suppose that makes sense—I also only discovered this when switching from OpenSSL to Rustls.

**Comment by youyuanwu** [comment]
This is the correct byte string to set in the client connector openssl api:
```rust
 connector.set_alpn_protos(ALPN_H2_WIRE)
```
The link in the above openssl documentation explains why 0x02 is needed.
